import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./context/portfolioContext";
import SideBar from "./components/sidebar";
import DynamicBackground from "./components/dynamic-background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <AppProvider>
          <div className="h-screen w-full relative flex flex-row">
            <SideBar/>
            <div className={'w-full flex flex-col relative z-1 col-span-3 p-10 w-[95%]'}>
              {children}
            </div>
          </div>
          <DynamicBackground/>
        </AppProvider>
      </body>
    </html>
  );
}
