import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider, useAppContext } from "./context/portfolioContext";
import SideBar from "./components/sidebar";
import ThreeScene from './components/ThreeScene'
import ViewModeToggler from "./components/viewModeToggler";
import Image from "next/image";
import WhatsAppMessenger from "./components/whatsapp_messager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <AppProvider>
          <div className="grid grid-cols-4">
            <ViewModeToggler />
            <WhatsAppMessenger />
            <ThreeScene/>
            <SideBar/>
            <div className={'w-full flex flex-col relative z-1 col-span-4'}>
              {children}
            </div>
          </div>
        </AppProvider>
        <div className="fixed inset-0 -z-10">
          <Image
            src="/pattern-hexagon-background-abstract-geometric-wallpaper-with-cover-web-shape_29971-522.avif"
            alt="Background"
            fill
            className="object-cover"
            priority
          />
        </div>

      </body>
    </html>
  );
}
